#!/usr/bin/env python
from pyqtgraph.Qt import QtGui, QtCore
import pyqtgraph as pg
import itertools
import subprocess
import os
import signal
import threading
import shlex, time
import sys


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class dateAxis(pg.AxisItem):
    def tickStrings(self, values, scale, spacing):
        strns = []
        rng = max(values)-min(values)
        string = '%M:%S'
        label1 = '%b %d -'
        label2 = ' %b %d, %Y'
        for x in values:
            try:
                strns.append(time.strftime(string, time.localtime(x)))
            except ValueError:  ## Windows can't handle dates before 1970
                strns.append('')
        try:
            label = time.strftime(label1, time.localtime(min(values)))+time.strftime(label2, time.localtime(max(values)))
        except ValueError:
            label = ''
        return strns


class uiMainWindow(object):
    def select_jobfile(self):        
        if (QtCore.QT_VERSION_STR >= "5"):
            jobfile = QtGui.QFileDialog.getOpenFileName()[0]
        else:
            jobfile = QtGui.QFileDialog.getOpenFileName()
        self.fio_jobfile_path.setText(jobfile)
        try:
            text = open('' + jobfile).read()
            self.fio_jobfile_contents.setPlainText(text)
        except IOError:
            pass
        self.browse_button.setChecked(False)
    def setup_ui(self, MainWindow):
        y_axis_read_iops=pg.AxisItem(orientation='left', showValues=True)
        y_axis_read_iops.setLabel('Read IOPs (IOP/s)<br><br>')
        y_axis_read_iops.setStyle(autoExpandTextSpace=False)
        y_axis_write_iops=pg.AxisItem(orientation='left')
        y_axis_write_iops.setLabel('<br>Write IOPs (IOP/s)<br><br>')
        y_axis_write_iops.setStyle(autoExpandTextSpace=False)
        y_axis_read_bw=pg.AxisItem(orientation='left')
        y_axis_read_bw.setLabel('Read BW (autoscale)<br><br>')
        y_axis_read_bw.setStyle(autoExpandTextSpace=False)
        y_axis_write_bw=pg.AxisItem(orientation='left')
        y_axis_write_bw.setLabel('<br>Write BW (autoscale)<br><br>')
        y_axis_write_bw.setStyle(autoExpandTextSpace=False)
        y_axis_read_lat=pg.AxisItem(orientation='left')
        y_axis_read_lat.setLabel('Read latency (ms)<br><br>')
        y_axis_read_lat.setStyle(autoExpandTextSpace=False)
        y_axis_write_lat=pg.AxisItem(orientation='left')
        y_axis_write_lat.setLabel('<br>Write latency (ms)<br><br>')
        y_axis_read_lat.setStyle(autoExpandTextSpace=False)
        x_axis_read_iops = dateAxis(orientation='bottom')
        x_axis_write_iops = dateAxis(orientation='bottom')
        x_axis_read_bw = dateAxis(orientation='bottom')
        x_axis_write_bw = dateAxis(orientation='bottom')
        x_axis_read_lat = dateAxis(orientation='bottom')
        x_axis_write_lat = dateAxis(orientation='bottom')
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 768)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 151, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 151, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 151, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_8.setMargin(3)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.splitter_3 = QtGui.QSplitter(self.centralWidget)
        self.splitter_3.setAccessibleName(_fromUtf8(""))
        self.splitter_3.setLineWidth(0)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setHandleWidth(0)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.splitter = QtGui.QSplitter(self.splitter_3)
        self.splitter.setAccessibleName(_fromUtf8(""))
        self.splitter.setLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(0)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.read_iops_plot = pg.PlotWidget(self.splitter, axisItems={'left': y_axis_read_iops, 'bottom':x_axis_read_iops})
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_iops_plot.sizePolicy().hasHeightForWidth())
        self.read_iops_plot.setSizePolicy(sizePolicy)
        self.read_iops_plot.setMinimumSize(QtCore.QSize(0, 0))
        self.read_iops_plot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.read_iops_plot.setBaseSize(QtCore.QSize(0, 0))
        self.read_iops_plot.setAccessibleName(_fromUtf8(""))
        self.read_iops_plot.setInteractive(True)
        self.read_iops_plot.setObjectName(_fromUtf8("read_iops_plot"))
        self.read_bw_plot = pg.PlotWidget(self.splitter, axisItems={'left': y_axis_read_bw, 'bottom':x_axis_read_bw})
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_bw_plot.sizePolicy().hasHeightForWidth())
        self.read_bw_plot.setSizePolicy(sizePolicy)
        self.read_bw_plot.setMinimumSize(QtCore.QSize(0, 0))
        self.read_bw_plot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.read_bw_plot.setBaseSize(QtCore.QSize(0, 0))
        self.read_bw_plot.setAccessibleName(_fromUtf8(""))
        self.read_bw_plot.setInteractive(True)
        self.read_bw_plot.setObjectName(_fromUtf8("read_bw_plot"))
        self.read_lat_plot = pg.PlotWidget(self.splitter, axisItems={'left': y_axis_read_lat, 'bottom':x_axis_read_lat})
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_lat_plot.sizePolicy().hasHeightForWidth())
        self.read_lat_plot.setSizePolicy(sizePolicy)
        self.read_lat_plot.setMinimumSize(QtCore.QSize(0, 0))
        self.read_lat_plot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.read_lat_plot.setBaseSize(QtCore.QSize(0, 0))
        self.read_lat_plot.setAccessibleName(_fromUtf8(""))
        self.read_lat_plot.setObjectName(_fromUtf8("read_lat_plot"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        self.splitter_2.setAccessibleName(_fromUtf8(""))
        self.splitter_2.setLineWidth(0)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(4)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.write_iops_plot = pg.PlotWidget(self.splitter_2, axisItems={'left': y_axis_write_iops, 'bottom':x_axis_write_iops})
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_iops_plot.sizePolicy().hasHeightForWidth())
        self.write_iops_plot.setSizePolicy(sizePolicy)
        self.write_iops_plot.setMinimumSize(QtCore.QSize(0, 0))
        self.write_iops_plot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.write_iops_plot.setBaseSize(QtCore.QSize(0, 0))
        self.write_iops_plot.setAccessibleName(_fromUtf8(""))
        self.write_iops_plot.setObjectName(_fromUtf8("write_iops_plot"))
        self.write_bw_plot = pg.PlotWidget(self.splitter_2, axisItems={'left': y_axis_write_bw, 'bottom':x_axis_write_bw})
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_bw_plot.sizePolicy().hasHeightForWidth())
        self.write_bw_plot.setSizePolicy(sizePolicy)
        self.write_bw_plot.setMinimumSize(QtCore.QSize(0, 0))
        self.write_bw_plot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.write_bw_plot.setBaseSize(QtCore.QSize(0, 0))
        self.write_bw_plot.setAccessibleName(_fromUtf8(""))
        self.write_bw_plot.setObjectName(_fromUtf8("write_bw_plot"))
        self.write_lat_plot = pg.PlotWidget(self.splitter_2, axisItems={'left': y_axis_write_lat, 'bottom':x_axis_write_lat})
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_lat_plot.sizePolicy().hasHeightForWidth())
        self.write_lat_plot.setSizePolicy(sizePolicy)
        self.write_lat_plot.setMinimumSize(QtCore.QSize(0, 0))
        self.write_lat_plot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.write_lat_plot.setBaseSize(QtCore.QSize(0, 0))
        self.write_lat_plot.setAccessibleName(_fromUtf8(""))
        self.write_lat_plot.setObjectName(_fromUtf8("write_lat_plot"))
        self.gridLayout_8.addWidget(self.splitter_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(180, 723))
        self.dockWidget.setMaximumSize(QtCore.QSize(180, 524287))
        self.dockWidget.setAccessibleName(_fromUtf8(""))
        self.dockWidget.setFloating(False)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setWindowTitle(_fromUtf8("Settings"))
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_6 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.frame_10 = QtGui.QFrame(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_10.setAccessibleName(_fromUtf8(""))
        self.frame_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_10)
        self.gridLayout_5.setMargin(2)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_11 = QtGui.QFrame(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_11.setAccessibleName(_fromUtf8(""))
        self.frame_11.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_11)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.start_button = QtGui.QPushButton(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.start_button.setFont(font)
        self.start_button.setAccessibleName(_fromUtf8(""))
        self.start_button.setStyleSheet(_fromUtf8(""))
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.gridLayout_2.addWidget(self.start_button, 0, 0, 1, 1)
        self.stop_button = QtGui.QPushButton(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stop_button.setFont(font)
        self.stop_button.setAccessibleName(_fromUtf8(""))
        self.stop_button.setStyleSheet(_fromUtf8(""))
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.gridLayout_2.addWidget(self.stop_button, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_11, 2, 0, 1, 2)
        self.frame = QtGui.QFrame(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setAccessibleName(_fromUtf8(""))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_8 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setAccessibleName(_fromUtf8(""))
        self.label_8.setStyleSheet(_fromUtf8(""))
        self.label_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_8.setFrameShadow(QtGui.QFrame.Plain)
        self.label_8.setLineWidth(-5)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setMargin(0)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.fio_jobfile_path = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fio_jobfile_path.sizePolicy().hasHeightForWidth())
        self.fio_jobfile_path.setSizePolicy(sizePolicy)
        self.fio_jobfile_path.setMinimumSize(QtCore.QSize(0, 0))
        self.fio_jobfile_path.setAccessibleName(_fromUtf8(""))
        self.fio_jobfile_path.setReadOnly(True)
        self.fio_jobfile_path.setObjectName(_fromUtf8("fio_jobfile_path"))
        self.gridLayout_7.addWidget(self.fio_jobfile_path, 1, 0, 1, 1)
        self.fio_jobfile_contents = QtGui.QPlainTextEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fio_jobfile_contents.sizePolicy().hasHeightForWidth())
        self.fio_jobfile_contents.setSizePolicy(sizePolicy)
        self.fio_jobfile_contents.setMinimumSize(QtCore.QSize(0, 0))
        self.fio_jobfile_contents.setAccessibleName(_fromUtf8(""))
        self.fio_jobfile_contents.setUndoRedoEnabled(False)
        self.fio_jobfile_contents.setReadOnly(True)
        self.fio_jobfile_contents.setObjectName(_fromUtf8("fio_jobfile_contents"))
        self.gridLayout_7.addWidget(self.fio_jobfile_contents, 2, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setAccessibleName(_fromUtf8(""))
        self.label_7.setStyleSheet(_fromUtf8(""))
        self.label_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_7.setFrameShadow(QtGui.QFrame.Plain)
        self.label_7.setLineWidth(0)
        self.label_7.setMidLineWidth(0)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_7.addWidget(self.label_7, 3, 0, 1, 1)
        self.fio_arguments = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fio_arguments.sizePolicy().hasHeightForWidth())
        self.fio_arguments.setSizePolicy(sizePolicy)
        self.fio_arguments.setMinimumSize(QtCore.QSize(0, 0))
        self.fio_arguments.setAccessibleName(_fromUtf8(""))
        self.fio_arguments.setObjectName(_fromUtf8("fio_arguments"))
        self.gridLayout_7.addWidget(self.fio_arguments, 4, 0, 1, 2)
        self.browse_button = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_button.sizePolicy().hasHeightForWidth())
        self.browse_button.setSizePolicy(sizePolicy)
        self.browse_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.browse_button.setFont(font)
        self.browse_button.setAccessibleName(_fromUtf8(""))
        self.browse_button.setStyleSheet(_fromUtf8(""))
        self.browse_button.setCheckable(True)
        self.browse_button.setChecked(False)
        self.browse_button.setAutoExclusive(False)
        self.browse_button.setObjectName(_fromUtf8("browse_button"))
        self.gridLayout_7.addWidget(self.browse_button, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setAccessibleName(_fromUtf8(""))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.frame_4 = QtGui.QFrame(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.read_iops_checkbox = QtGui.QCheckBox(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_iops_checkbox.sizePolicy().hasHeightForWidth())
        self.read_iops_checkbox.setSizePolicy(sizePolicy)
        self.read_iops_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.read_iops_checkbox.setFont(font)
        self.read_iops_checkbox.setStyleSheet(_fromUtf8(""))
        self.read_iops_checkbox.setChecked(True)
        self.read_iops_checkbox.setAutoExclusive(False)
        self.read_iops_checkbox.setTristate(False)
        self.read_iops_checkbox.setObjectName(_fromUtf8("read_iops_checkbox"))
        self.gridLayout_12.addWidget(self.read_iops_checkbox, 0, 0, 2, 1)
        self.read_iops_total_checkbox = QtGui.QCheckBox(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_iops_total_checkbox.sizePolicy().hasHeightForWidth())
        self.read_iops_total_checkbox.setSizePolicy(sizePolicy)
        self.read_iops_total_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.read_iops_total_checkbox.setFont(font)
        self.read_iops_total_checkbox.setStyleSheet(_fromUtf8(""))
        self.read_iops_total_checkbox.setChecked(True)
        self.read_iops_total_checkbox.setObjectName(_fromUtf8("read_iops_total_checkbox"))
        self.gridLayout_12.addWidget(self.read_iops_total_checkbox, 0, 1, 1, 1)
        self.read_iops_threads_checkbox = QtGui.QCheckBox(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_iops_threads_checkbox.sizePolicy().hasHeightForWidth())
        self.read_iops_threads_checkbox.setSizePolicy(sizePolicy)
        self.read_iops_threads_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.read_iops_threads_checkbox.setFont(font)
        self.read_iops_threads_checkbox.setStyleSheet(_fromUtf8(""))
        self.read_iops_threads_checkbox.setChecked(False)
        self.read_iops_threads_checkbox.setObjectName(_fromUtf8("read_iops_threads_checkbox"))
        self.gridLayout_12.addWidget(self.read_iops_threads_checkbox, 1, 1, 1, 1)
        self.gridLayout_11.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_5 = QtGui.QFrame(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_13 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.read_bw_checkbox = QtGui.QCheckBox(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_bw_checkbox.sizePolicy().hasHeightForWidth())
        self.read_bw_checkbox.setSizePolicy(sizePolicy)
        self.read_bw_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.read_bw_checkbox.setFont(font)
        self.read_bw_checkbox.setStyleSheet(_fromUtf8(""))
        self.read_bw_checkbox.setChecked(True)
        self.read_bw_checkbox.setObjectName(_fromUtf8("read_bw_checkbox"))
        self.gridLayout_13.addWidget(self.read_bw_checkbox, 0, 0, 2, 1)
        self.read_bw_total_checkbox = QtGui.QCheckBox(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_bw_total_checkbox.sizePolicy().hasHeightForWidth())
        self.read_bw_total_checkbox.setSizePolicy(sizePolicy)
        self.read_bw_total_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.read_bw_total_checkbox.setFont(font)
        self.read_bw_total_checkbox.setStyleSheet(_fromUtf8(""))
        self.read_bw_total_checkbox.setChecked(True)
        self.read_bw_total_checkbox.setObjectName(_fromUtf8("read_bw_total_checkbox"))
        self.gridLayout_13.addWidget(self.read_bw_total_checkbox, 0, 1, 1, 1)
        self.read_bw_threads_checkbox = QtGui.QCheckBox(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_bw_threads_checkbox.sizePolicy().hasHeightForWidth())
        self.read_bw_threads_checkbox.setSizePolicy(sizePolicy)
        self.read_bw_threads_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.read_bw_threads_checkbox.setFont(font)
        self.read_bw_threads_checkbox.setStyleSheet(_fromUtf8(""))
        self.read_bw_threads_checkbox.setObjectName(_fromUtf8("read_bw_threads_checkbox"))
        self.gridLayout_13.addWidget(self.read_bw_threads_checkbox, 1, 1, 1, 1)
        self.gridLayout_11.addWidget(self.frame_5, 1, 0, 1, 1)
        self.frame_9 = QtGui.QFrame(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setFrameShape(QtGui.QFrame.Box)
        self.frame_9.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.read_lat_checkbox = QtGui.QCheckBox(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_lat_checkbox.sizePolicy().hasHeightForWidth())
        self.read_lat_checkbox.setSizePolicy(sizePolicy)
        self.read_lat_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.read_lat_checkbox.setFont(font)
        self.read_lat_checkbox.setStyleSheet(_fromUtf8(""))
        self.read_lat_checkbox.setChecked(True)
        self.read_lat_checkbox.setObjectName(_fromUtf8("read_lat_checkbox"))
        self.gridLayout_14.addWidget(self.read_lat_checkbox, 0, 0, 2, 1)
        self.read_lat_max_checkbox = QtGui.QCheckBox(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_lat_max_checkbox.sizePolicy().hasHeightForWidth())
        self.read_lat_max_checkbox.setSizePolicy(sizePolicy)
        self.read_lat_max_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.read_lat_max_checkbox.setFont(font)
        self.read_lat_max_checkbox.setStyleSheet(_fromUtf8(""))
        self.read_lat_max_checkbox.setChecked(False)
        self.read_lat_max_checkbox.setObjectName(_fromUtf8("read_lat_max_checkbox"))
        self.gridLayout_14.addWidget(self.read_lat_max_checkbox, 0, 1, 1, 1)
        self.read_lat_threads_checkbox = QtGui.QCheckBox(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_lat_threads_checkbox.sizePolicy().hasHeightForWidth())
        self.read_lat_threads_checkbox.setSizePolicy(sizePolicy)
        self.read_lat_threads_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.read_lat_threads_checkbox.setFont(font)
        self.read_lat_threads_checkbox.setStyleSheet(_fromUtf8(""))
        self.read_lat_threads_checkbox.setChecked(True)
        self.read_lat_threads_checkbox.setObjectName(_fromUtf8("read_lat_threads_checkbox"))
        self.gridLayout_14.addWidget(self.read_lat_threads_checkbox, 1, 1, 1, 1)
        self.gridLayout_11.addWidget(self.frame_9, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout = QtGui.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_6 = QtGui.QFrame(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setAccessibleName(_fromUtf8(""))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.write_iops_checkbox = QtGui.QCheckBox(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_iops_checkbox.sizePolicy().hasHeightForWidth())
        self.write_iops_checkbox.setSizePolicy(sizePolicy)
        self.write_iops_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.write_iops_checkbox.setFont(font)
        self.write_iops_checkbox.setAccessibleName(_fromUtf8(""))
        self.write_iops_checkbox.setStyleSheet(_fromUtf8(""))
        self.write_iops_checkbox.setChecked(True)
        self.write_iops_checkbox.setObjectName(_fromUtf8("write_iops_checkbox"))
        self.gridLayout_10.addWidget(self.write_iops_checkbox, 0, 0, 2, 1)
        self.write_iops_total_checkbox = QtGui.QCheckBox(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_iops_total_checkbox.sizePolicy().hasHeightForWidth())
        self.write_iops_total_checkbox.setSizePolicy(sizePolicy)
        self.write_iops_total_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.write_iops_total_checkbox.setFont(font)
        self.write_iops_total_checkbox.setAccessibleName(_fromUtf8(""))
        self.write_iops_total_checkbox.setStyleSheet(_fromUtf8(""))
        self.write_iops_total_checkbox.setChecked(True)
        self.write_iops_total_checkbox.setObjectName(_fromUtf8("write_iops_total_checkbox"))
        self.gridLayout_10.addWidget(self.write_iops_total_checkbox, 0, 1, 1, 1)
        self.write_iops_threads_checkbox = QtGui.QCheckBox(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_iops_threads_checkbox.sizePolicy().hasHeightForWidth())
        self.write_iops_threads_checkbox.setSizePolicy(sizePolicy)
        self.write_iops_threads_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.write_iops_threads_checkbox.setFont(font)
        self.write_iops_threads_checkbox.setAccessibleName(_fromUtf8(""))
        self.write_iops_threads_checkbox.setStyleSheet(_fromUtf8(""))
        self.write_iops_threads_checkbox.setObjectName(_fromUtf8("write_iops_threads_checkbox"))
        self.gridLayout_10.addWidget(self.write_iops_threads_checkbox, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_6, 0, 0, 1, 1)
        self.frame_7 = QtGui.QFrame(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_7.setAccessibleName(_fromUtf8(""))
        self.frame_7.setFrameShape(QtGui.QFrame.Box)
        self.frame_7.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.write_bw_checkbox = QtGui.QCheckBox(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_bw_checkbox.sizePolicy().hasHeightForWidth())
        self.write_bw_checkbox.setSizePolicy(sizePolicy)
        self.write_bw_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.write_bw_checkbox.setFont(font)
        self.write_bw_checkbox.setAccessibleName(_fromUtf8(""))
        self.write_bw_checkbox.setStyleSheet(_fromUtf8(""))
        self.write_bw_checkbox.setChecked(True)
        self.write_bw_checkbox.setObjectName(_fromUtf8("write_bw_checkbox"))
        self.gridLayout_9.addWidget(self.write_bw_checkbox, 0, 0, 2, 1)
        self.write_bw_total_checkbox = QtGui.QCheckBox(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_bw_total_checkbox.sizePolicy().hasHeightForWidth())
        self.write_bw_total_checkbox.setSizePolicy(sizePolicy)
        self.write_bw_total_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.write_bw_total_checkbox.setFont(font)
        self.write_bw_total_checkbox.setAccessibleName(_fromUtf8(""))
        self.write_bw_total_checkbox.setStyleSheet(_fromUtf8(""))
        self.write_bw_total_checkbox.setChecked(True)
        self.write_bw_total_checkbox.setObjectName(_fromUtf8("write_bw_total_checkbox"))
        self.gridLayout_9.addWidget(self.write_bw_total_checkbox, 0, 1, 1, 1)
        self.write_bw_threads_checkbox = QtGui.QCheckBox(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_bw_threads_checkbox.sizePolicy().hasHeightForWidth())
        self.write_bw_threads_checkbox.setSizePolicy(sizePolicy)
        self.write_bw_threads_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.write_bw_threads_checkbox.setFont(font)
        self.write_bw_threads_checkbox.setAccessibleName(_fromUtf8(""))
        self.write_bw_threads_checkbox.setStyleSheet(_fromUtf8(""))
        self.write_bw_threads_checkbox.setObjectName(_fromUtf8("write_bw_threads_checkbox"))
        self.gridLayout_9.addWidget(self.write_bw_threads_checkbox, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_7, 1, 0, 1, 1)
        self.frame_8 = QtGui.QFrame(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setAccessibleName(_fromUtf8(""))
        self.frame_8.setFrameShape(QtGui.QFrame.Box)
        self.frame_8.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.write_lat_checkbox = QtGui.QCheckBox(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_lat_checkbox.sizePolicy().hasHeightForWidth())
        self.write_lat_checkbox.setSizePolicy(sizePolicy)
        self.write_lat_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.write_lat_checkbox.setFont(font)
        self.write_lat_checkbox.setAccessibleName(_fromUtf8(""))
        self.write_lat_checkbox.setStyleSheet(_fromUtf8(""))
        self.write_lat_checkbox.setChecked(True)
        self.write_lat_checkbox.setObjectName(_fromUtf8("write_lat_checkbox"))
        self.gridLayout_4.addWidget(self.write_lat_checkbox, 0, 0, 2, 1)
        self.write_lat_max_checkbox = QtGui.QCheckBox(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_lat_max_checkbox.sizePolicy().hasHeightForWidth())
        self.write_lat_max_checkbox.setSizePolicy(sizePolicy)
        self.write_lat_max_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.write_lat_max_checkbox.setFont(font)
        self.write_lat_max_checkbox.setAccessibleName(_fromUtf8(""))
        self.write_lat_max_checkbox.setStyleSheet(_fromUtf8(""))
        self.write_lat_max_checkbox.setChecked(False)
        self.write_lat_max_checkbox.setObjectName(_fromUtf8("write_lat_max_checkbox"))
        self.gridLayout_4.addWidget(self.write_lat_max_checkbox, 0, 1, 1, 1)
        self.write_lat_threads_checkbox = QtGui.QCheckBox(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_lat_threads_checkbox.sizePolicy().hasHeightForWidth())
        self.write_lat_threads_checkbox.setSizePolicy(sizePolicy)
        self.write_lat_threads_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.write_lat_threads_checkbox.setFont(font)
        self.write_lat_threads_checkbox.setAccessibleName(_fromUtf8(""))
        self.write_lat_threads_checkbox.setStyleSheet(_fromUtf8(""))
        self.write_lat_threads_checkbox.setObjectName(_fromUtf8("write_lat_threads_checkbox"))
        self.write_lat_threads_checkbox.setChecked(True)
        self.gridLayout_4.addWidget(self.write_lat_threads_checkbox, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_8, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 1, 0, 1, 2)
        self.gridLayout_6.addWidget(self.frame_10, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionPlot_Area = QtGui.QAction(MainWindow)
        self.actionPlot_Area.setObjectName(_fromUtf8("actionPlot_Area"))
        self.browse_button.clicked.connect(self.select_jobfile)
        self.fio_arguments.setText('--status-interval=1')
        self.read_iops_plot.setLimits(yMin=0, xMin=0)
        self.write_iops_plot.setLimits(yMin=0, xMin=0)
        self.read_bw_plot.setLimits(yMin=0, xMin=0)
        self.write_bw_plot.setLimits(yMin=0, xMin=0)
        self.read_lat_plot.setLimits(yMin=0, xMin=0)
        self.write_lat_plot.setLimits(yMin=0, xMin=0)
        self.read_iops_plot.showGrid(x=True, y=True, alpha=0.2)
        self.write_iops_plot.showGrid(x=True, y=True, alpha=0.2)
        self.read_bw_plot.showGrid(x=True, y=True, alpha=0.2)
        self.write_bw_plot.showGrid(x=True, y=True, alpha=0.2)
        self.read_lat_plot.showGrid(x=True, y=True, alpha=0.2)
        self.write_lat_plot.showGrid(x=True, y=True, alpha=0.2)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "FIO visualizing tool", None))
        self.start_button.setText(_translate("MainWindow", "START", None))
        self.stop_button.setText(_translate("MainWindow", "STOP", None))
        self.label_8.setText(_translate("MainWindow", "Jobfile:", None))
        self.label_7.setText(_translate("MainWindow", "FIO arguments:", None))
        self.browse_button.setText(_translate("MainWindow", "Browse", None))
        self.read_iops_checkbox.setText(_translate("MainWindow", "IOPS", None))
        self.read_iops_total_checkbox.setText(_translate("MainWindow", "Total", None))
        self.read_iops_threads_checkbox.setText(_translate("MainWindow", "All", None))
        self.read_bw_checkbox.setText(_translate("MainWindow", "BW", None))
        self.read_bw_total_checkbox.setText(_translate("MainWindow", "Total", None))
        self.read_bw_threads_checkbox.setText(_translate("MainWindow", "All", None))
        self.read_lat_checkbox.setText(_translate("MainWindow", "LAT", None))
        self.read_lat_max_checkbox.setText(_translate("MainWindow", "Peak\n"
"(max of\n"
"clat_max)", None))
        self.read_lat_threads_checkbox.setText(_translate("MainWindow", "All clat_avg", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Read", None))
        self.write_iops_checkbox.setText(_translate("MainWindow", "IOPS", None))
        self.write_iops_total_checkbox.setText(_translate("MainWindow", "Total", None))
        self.write_iops_threads_checkbox.setText(_translate("MainWindow", "All", None))
        self.write_bw_checkbox.setText(_translate("MainWindow", "BW", None))
        self.write_bw_total_checkbox.setText(_translate("MainWindow", "Total", None))
        self.write_bw_threads_checkbox.setText(_translate("MainWindow", "All", None))
        self.write_lat_checkbox.setText(_translate("MainWindow", "LAT", None))
        self.write_lat_max_checkbox.setText(_translate("MainWindow", "Peak\n"
"(max of\n"
"clat_max)", None))
        self.write_lat_threads_checkbox.setText(_translate("MainWindow", "All clat_avg", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Write", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionPlot_Area.setText(_translate("MainWindow", "Plot Area", None))

def start_fio():
    global parsing_thread, fio_process, timer, read_iops_all, read_bw_all, write_iops_all, write_bw_all, read_lat_mean_all, read_lat_max_all, write_lat_mean_all, write_lat_max_all, read_iops_total, read_bw_total, write_iops_total, write_bw_total, read_lat_peak, write_lat_peak
    if find_numjobs() != False:
        fio_command='fio --minimal --eta=0 ' + str(ui.fio_arguments.text())+ ' ' + str(ui.fio_jobfile_path.text())
        args=shlex.split(fio_command)
        fio_process = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True, preexec_fn=os.setpgrp)
        read_iops_all = [[] for i in itertools.repeat(None, numjobs)]
        read_bw_all = [[] for i in itertools.repeat(None, numjobs)]
        write_iops_all = [[] for i in itertools.repeat(None, numjobs)]
        write_bw_all = [[] for i in itertools.repeat(None, numjobs)]
        read_lat_mean_all = [[] for i in itertools.repeat(None, numjobs)]
        read_lat_max_all = [[] for i in itertools.repeat(None, numjobs)]
        write_lat_mean_all = [[] for i in itertools.repeat(None, numjobs)]
        write_lat_max_all= [[] for i in itertools.repeat(None, numjobs)]
        read_iops_total = []
        read_bw_total = []
        write_iops_total = []
        write_bw_total = []
        read_lat_peak = []
        write_lat_peak = []
        parsing_thread = threading.Thread(target=parse_fio_output, args=())
        parsing_thread.start()
        timer = QtCore.QTimer()
        timer.timeout.connect(update)
        timer.start(1000)

def kill_fio():
    try:
        os.killpg(fio_process.pid, signal.SIGTERM)
        fio_process_output, fio_process_error = fio_process.communicate()
    except:
        pass

def find_numjobs():
    global numjobs
    numjobs=None
    msgBox = QtGui.QMessageBox()
    arguments=str(ui.fio_arguments.text()).strip()
    jobfile=str(ui.fio_jobfile_path.text())
    if arguments != '':
        if '--numjobs' in arguments:
            for i in arguments.split('--'):
                if 'numjobs' in i:
                    numjobs = int(i.split('=')[1])
    if jobfile != '':
        parse_jobfile_test = subprocess.Popen(['fio', '--showcmd', jobfile], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        #parse_jobfile_test_output, parse_jobfile_test_error = parse_jobfile_test.communicate()
        parse_jobfile_test_output = parse_jobfile_test.communicate()[0]
        parse_jobfile_test_output = parse_jobfile_test_output.decode("utf-8")
        #reply = msgBox.information(None, '', parse_jobfile_test_output)                                
        if '--numjobs' in parse_jobfile_test_output:
            for i in parse_jobfile_test_output.split('--'):
                if 'numjobs' in i:
                    numjobs = int(i.split('=')[1])
#Change numjobs for multi-job file here

    if numjobs == None:
        warningbox = QtGui.QMessageBox()
        reply = warningbox.question(warningbox, 'Warning', 'Failed to find numjobs value. If not defined, FIO will be launched with --numjobs=1. Are you sure you want to continue?', QtGui.QMessageBox.Yes | QtGui.QMessageBox.No, QtGui.QMessageBox.No)
        if reply == warningbox.Yes:
            numjobs = 1
        if reply == warningbox.No:
            return False
    else:
        reply = msgBox.question(None, '',  "Starting '" + str(numjobs) + "' simultaneous jobs")


def parse_fio_output():
    global exit_code
    thread_number = 0
    while fio_process.poll() == None:
        exit_code=None
        line = fio_process.stdout.readline()
        parsedline = line.split(";")
        if len(parsedline) == 130:
            ui.start_button.setEnabled(False)
            ui.stop_button.setEnabled(True)
            if thread_number < numjobs:
                read_iops_all[thread_number].append(int(parsedline[7]))
                read_bw_all[thread_number].append(int(parsedline[6]))
                write_iops_all[thread_number].append(int(parsedline[48]))
                write_bw_all[thread_number].append(int(parsedline[47]))
                read_lat_mean_all[thread_number].append(
                    float(parsedline[15])/1000)
                read_lat_max_all[thread_number].append(
                    float(parsedline[14])/1000)
                write_lat_mean_all[thread_number].append(
                    float(parsedline[56])/1000)
                write_lat_max_all[thread_number].append(
                    float(parsedline[55])/1000)
                thread_number += 1
            if thread_number == numjobs:
                # Calculate sums and maximums only if numjobs > 1
                if numjobs > 1:
                    tmp1 = []
                    for x in range(0, numjobs):
                        tmp1.append(read_iops_all[x][-1])
                    tmp2 = []
                    for x in range(0, numjobs):
                        tmp2.append(read_bw_all[x][-1])
                    tmp3 = []
                    for x in range(0, numjobs):
                        tmp3.append(write_iops_all[x][-1])
                    tmp4 = []
                    for x in range(0, numjobs):
                        tmp4.append(write_bw_all[x][-1])
                    tmp5 = []
                    for x in range(0, numjobs):
                        tmp5.append(read_lat_max_all[x][-1])
                    tmp6 = []
                    for x in range(0, numjobs):
                        tmp6.append(write_lat_max_all[x][-1])
                    read_iops_total.append(sum(tmp1))
                    read_bw_total.append(sum(tmp2))
                    write_iops_total.append(sum(tmp3))
                    write_bw_total.append(sum(tmp4))
                    read_lat_peak.append(max(tmp5))
                    write_lat_peak.append(max(tmp6))
                thread_number = 0
        else:
            exit_code=fio_process.poll()
            ui.start_button.setEnabled(True)
            ui.stop_button.setEnabled(False)
    else:
        exit_code=fio_process.poll()
        ui.start_button.setEnabled(True)
        ui.stop_button.setEnabled(False)

def update():
    global timer
    if exit_code==None:
        if numjobs > 1:
            if ui.read_iops_checkbox.isChecked():
                ui.read_iops_plot.clear()
                if ui.read_iops_total_checkbox.isChecked():
                    ui.read_iops_plot.plot(pen='#00aeef', symbolBrush='#00aeef').setData(
                        read_iops_total)
                if ui.read_iops_threads_checkbox.isChecked():
                    for thread_stat_list in read_iops_all:
                        ui.read_iops_plot.plot(pen=None, symbolBrush='#00aeef').setData(
                            thread_stat_list)
            if ui.write_iops_checkbox.isChecked():
                ui.write_iops_plot.clear()
                if ui.write_iops_total_checkbox.isChecked():
                    ui.write_iops_plot.plot(pen='#00aeef', symbolBrush='#00aeef').setData(
                        write_iops_total)
                if ui.write_iops_threads_checkbox.isChecked():
                    for thread_stat_list in write_iops_all:
                        ui.write_iops_plot.plot(pen=None, symbolBrush='#00aeef').setData(
                            thread_stat_list)
            if ui.read_bw_checkbox.isChecked():
                ui.read_bw_plot.clear()
                if ui.read_bw_total_checkbox.isChecked():
                    ui.read_bw_plot.plot(pen='#fd9613', symbolBrush='#fd9613').setData(
                        read_bw_total)
                if ui.read_bw_threads_checkbox.isChecked():
                    for thread_stat_list in read_bw_all:
                        ui.read_bw_plot.plot(pen=None, symbolBrush='#fd9613').setData(
                            thread_stat_list)
            if ui.write_bw_checkbox.isChecked():
                ui.write_bw_plot.clear()
                if ui.write_bw_total_checkbox.isChecked():
                    ui.write_bw_plot.plot(pen='#fd9613', symbolBrush='#fd9613').setData(
                        write_bw_total)
                if ui.write_bw_threads_checkbox.isChecked():
                    for thread_stat_list in write_bw_all:
                        ui.write_bw_plot.plot(pen=None, symbolBrush='#fd9613').setData(
                            thread_stat_list)
            if ui.read_lat_checkbox.isChecked():
                ui.read_lat_plot.clear()
                if ui.read_lat_max_checkbox.isChecked():
                    ui.read_lat_plot.plot(pen='#004280', symbolBrush='#004280').setData(
                        read_lat_peak)
                if ui.read_lat_threads_checkbox.isChecked():
                    for thread_stat_list in read_lat_mean_all:
                        ui.read_lat_plot.plot(pen=None, symbolBrush='#004280').setData(
                            thread_stat_list)
            if ui.write_lat_checkbox.isChecked():
                ui.write_lat_plot.clear()
                if ui.write_lat_max_checkbox.isChecked():
                    ui.write_lat_plot.plot(pen='#004280', symbolBrush='#004280').setData(
                        write_lat_peak)
                if ui.write_lat_threads_checkbox.isChecked():
                    for thread_stat_list in write_lat_mean_all:
                        ui.write_lat_plot.plot(pen=None, symbolBrush='#004280').setData(
                            thread_stat_list)
        else:
            ui.read_iops_threads_checkbox.setEnabled(False)
            ui.read_iops_total_checkbox.setEnabled(False)
            ui.write_iops_threads_checkbox.setEnabled(False)
            ui.write_iops_total_checkbox.setEnabled(False)
            ui.read_bw_threads_checkbox.setEnabled(False)
            ui.read_bw_total_checkbox.setEnabled(False)
            ui.write_bw_total_checkbox.setEnabled(False)
            ui.write_bw_threads_checkbox.setEnabled(False)
            if ui.read_iops_checkbox.isChecked():
                ui.read_iops_plot.clear()
                ui.read_iops_plot.plot(pen='#00aeef', symbolBrush='#00aeef').setData(
                    read_iops_all[0])

            if ui.write_iops_checkbox.isChecked():
                ui.write_iops_plot.clear()
                ui.write_iops_plot.plot(pen='#00aeef', symbolBrush='#00aeef').setData(
                    write_iops_all[0])

            if ui.read_bw_checkbox.isChecked():
                ui.read_bw_plot.clear()
                ui.read_bw_plot.plot(pen='#fd9613', symbolBrush='#fd9613').setData(
                    read_bw_all[0])

            if ui.write_bw_checkbox.isChecked():
                ui.write_bw_plot.clear()
                ui.write_bw_plot.plot(pen='#fd9613', symbolBrush='#fd9613').setData(
                    write_bw_all[0])

            if ui.read_lat_checkbox.isChecked():
                ui.read_lat_plot.clear()
                if ui.read_lat_max_checkbox.isChecked():
                   ui. read_lat_plot.plot(pen='#004280', symbolBrush='#004280').setData(read_lat_max_all[0])
                if ui.read_lat_threads_checkbox.isChecked():
                    ui.read_lat_plot.plot(pen=None, symbolBrush='#004280').setData(read_lat_mean_all[0])

            if ui.write_lat_checkbox.isChecked():
                ui.write_lat_plot.clear()
                if ui.write_lat_max_checkbox.isChecked():
                    ui.write_lat_plot.plot(pen='#004280', symbolBrush='#004280').setData(write_lat_max_all[0])
                if ui.write_lat_threads_checkbox.isChecked():
                    ui.write_lat_plot.plot(pen=None, symbolBrush='#004280').setData(write_lat_mean_all[0])
    else:
        ui.read_iops_threads_checkbox.setEnabled(True)
        ui.read_iops_total_checkbox.setEnabled(True)
        ui.write_iops_threads_checkbox.setEnabled(True)
        ui.write_iops_total_checkbox.setEnabled(True)
        ui.read_bw_threads_checkbox.setEnabled(True)
        ui.read_bw_total_checkbox.setEnabled(True)
        ui.write_bw_total_checkbox.setEnabled(True)
        ui.write_bw_threads_checkbox.setEnabled(True)
        if exit_code==0:
            messagebox = QtGui.QMessageBox()
            messagebox.information(messagebox, 'Informational', 'FIO succefully finished with exit code: '+str(exit_code))
            timer.stop()
        elif exit_code==128:
            messagebox = QtGui.QMessageBox()
            messagebox.information(messagebox, 'Informational', 'FIO was terminated by user, exit code: '+str(exit_code))
            timer.stop()
        else:
            fio_process_output, fio_process_error = fio_process.communicate()
            messagebox = QtGui.QMessageBox()
            messagebox.critical(messagebox, 'Informational', 'FIO was terminated with exit code: '+str(exit_code)+'\n\nSTDERR :'+str(fio_process_error))
            timer.stop()

def read_iops_checkbox_handler():
    if ui.read_iops_checkbox.isChecked():
        ui.read_iops_threads_checkbox.setEnabled(True)
        ui.read_iops_total_checkbox.setEnabled(True)
        ui.read_iops_plot.show()
    else:
        ui.read_iops_threads_checkbox.setEnabled(False)
        ui.read_iops_total_checkbox.setEnabled(False)
        ui.read_iops_plot.hide()

def write_iops_checkbox_handler():
    if ui.write_iops_checkbox.isChecked():
        ui.write_iops_threads_checkbox.setEnabled(True)
        ui.write_iops_total_checkbox.setEnabled(True)
        ui.write_iops_plot.show()
    else:
        ui.write_iops_threads_checkbox.setEnabled(False)
        ui.write_iops_total_checkbox.setEnabled(False)
        ui.write_iops_plot.hide()

def read_bw_checkbox_handler():
    if ui.read_bw_checkbox.isChecked():
        ui.read_bw_threads_checkbox.setEnabled(True)
        ui.read_bw_total_checkbox.setEnabled(True)
        ui.read_bw_plot.show()
    else:
        ui.read_bw_threads_checkbox.setEnabled(False)
        ui.read_bw_total_checkbox.setEnabled(False)
        ui.read_bw_plot.hide()

def write_bw_checkbox_handler():
    if ui.write_bw_checkbox.isChecked():
        ui.write_bw_threads_checkbox.setEnabled(True)
        ui.write_bw_total_checkbox.setEnabled(True)
        ui.write_bw_plot.show()
    else:
        ui.write_bw_threads_checkbox.setEnabled(False)
        ui.write_bw_total_checkbox.setEnabled(False)
        ui.write_bw_plot.hide()

def read_lat_checkbox_handler():
    if ui.read_lat_checkbox.isChecked():
        ui.read_lat_threads_checkbox.setEnabled(True)
        ui.read_lat_max_checkbox.setEnabled(True)
        ui.read_lat_plot.show()
    else:
        ui.read_lat_threads_checkbox.setEnabled(False)
        ui.read_lat_max_checkbox.setEnabled(False)
        ui.read_lat_plot.hide()

def write_lat_checkbox_handler():
    if ui.write_lat_checkbox.isChecked():
        ui.write_lat_threads_checkbox.setEnabled(True)
        ui.write_lat_max_checkbox.setEnabled(True)
        ui.write_lat_plot.show()
    else:
        ui.write_lat_threads_checkbox.setEnabled(False)
        ui.write_lat_max_checkbox.setEnabled(False)
        ui.write_lat_plot.hide()

application = QtGui.QApplication([])
#pg.setConfigOptions(antialias=True)
pg.setConfigOptions(foreground='k')
pg.setConfigOptions(background=(227, 227, 227))
window = QtGui.QMainWindow()
ui = uiMainWindow()
ui.setup_ui(window)
window.show()
ui.read_iops_checkbox.stateChanged.connect(read_iops_checkbox_handler)
ui.write_iops_checkbox.stateChanged.connect(write_iops_checkbox_handler)
ui.read_bw_checkbox.stateChanged.connect(read_bw_checkbox_handler)
ui.write_bw_checkbox.stateChanged.connect(write_bw_checkbox_handler)
ui.read_lat_checkbox.stateChanged.connect(read_lat_checkbox_handler)
ui.write_lat_checkbox.stateChanged.connect(write_lat_checkbox_handler)
ui.start_button.clicked.connect(start_fio)
ui.stop_button.clicked.connect(kill_fio)
QtGui.QApplication.instance().exec_()

def main(argv=None):
    if argv is None:
        argv = sys.argv
if __name__ == "__main__":
    sys.exit(main())
